name: GutHubAction Demo
on: [push]
jobs:
  Explore-github-Actions:
    runs-on:  ip-172-31-68-167
    steps:
      - run: echo "hai this is a sample command"
  Explore-github-Actions-Sample:
    runs-on:  ubuntu-latest
    steps:
      - run: echo "hai this is a sample command for second job"

